kind: pipeline
type: ssh
name: connect-master

trigger:
  branch:
    - master

server:
  host:
    from_secret: host-bb
  user:
    from_secret: user-bb
  password:
    from_secret: password-bb

steps:
  - name: deploy-master
    # environment:
    #   PORTS: 5001:5000
    #   BRANCH: master
    commands:
      # - curl -s http://whatismijnip.nl |cut -d " " -f 5
      - cd /root/adflasher.ru
      - git checkout master
      - git pull
      - docker-compose up -d --build
      - docker builder prune
      - docker image prune
      - docker volume prune
