version: "3"
services:
  react:
    container_name: adflasher__task4
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3031:3000
    environment:
      - NODE_ENV=production
